var apiKey = '888b9ccf3d084dc8aaa7543644aa1f6f',
    exchangeRates;

/* TODO: Rewrite to promises */

var getCurrencies = function() {
    var currencies = {
        "AED": "United Arab Emirates Dirham",
        "AFN": "Afghan Afghani",
        "ALL": "Albanian Lek",
        "AMD": "Armenian Dram",
        "ANG": "Netherlands Antillean Guilder",
        "AOA": "Angolan Kwanza",
        "ARS": "Argentine Peso",
        "AUD": "Australian Dollar",
        "AWG": "Aruban Florin",
        "AZN": "Azerbaijani Manat",
        "BAM": "Bosnia-Herzegovina Convertible Mark",
        "BBD": "Barbadian Dollar",
        "BDT": "Bangladeshi Taka",
        "BGN": "Bulgarian Lev",
        "BHD": "Bahraini Dinar",
        "BIF": "Burundian Franc",
        "BMD": "Bermudan Dollar",
        "BND": "Brunei Dollar",
        "BOB": "Bolivian Boliviano",
        "BRL": "Brazilian Real",
        "BSD": "Bahamian Dollar",
        "BTC": "Bitcoin",
        "BTN": "Bhutanese Ngultrum",
        "BWP": "Botswanan Pula",
        "BYR": "Belarusian Ruble",
        "BZD": "Belize Dollar",
        "CAD": "Canadian Dollar",
        "CDF": "Congolese Franc",
        "CHF": "Swiss Franc",
        "CLF": "Chilean Unit of Account (UF)",
        "CLP": "Chilean Peso",
        "CNY": "Chinese Yuan",
        "COP": "Colombian Peso",
        "CRC": "Costa Rican Colón",
        "CUC": "Cuban Convertible Peso",
        "CUP": "Cuban Peso",
        "CVE": "Cape Verdean Escudo",
        "CZK": "Czech Republic Koruna",
        "DJF": "Djiboutian Franc",
        "DKK": "Danish Krone",
        "DOP": "Dominican Peso",
        "DZD": "Algerian Dinar",
        "EEK": "Estonian Kroon",
        "EGP": "Egyptian Pound",
        "ERN": "Eritrean Nakfa",
        "ETB": "Ethiopian Birr",
        "EUR": "Euro",
        "FJD": "Fijian Dollar",
        "FKP": "Falkland Islands Pound",
        "GBP": "British Pound Sterling",
        "GEL": "Georgian Lari",
        "GGP": "Guernsey Pound",
        "GHS": "Ghanaian Cedi",
        "GIP": "Gibraltar Pound",
        "GMD": "Gambian Dalasi",
        "GNF": "Guinean Franc",
        "GTQ": "Guatemalan Quetzal",
        "GYD": "Guyanaese Dollar",
        "HKD": "Hong Kong Dollar",
        "HNL": "Honduran Lempira",
        "HRK": "Croatian Kuna",
        "HTG": "Haitian Gourde",
        "HUF": "Hungarian Forint",
        "IDR": "Indonesian Rupiah",
        "ILS": "Israeli New Sheqel",
        "IMP": "Manx pound",
        "INR": "Indian Rupee",
        "IQD": "Iraqi Dinar",
        "IRR": "Iranian Rial",
        "ISK": "Icelandic Króna",
        "JEP": "Jersey Pound",
        "JMD": "Jamaican Dollar",
        "JOD": "Jordanian Dinar",
        "JPY": "Japanese Yen",
        "KES": "Kenyan Shilling",
        "KGS": "Kyrgystani Som",
        "KHR": "Cambodian Riel",
        "KMF": "Comorian Franc",
        "KPW": "North Korean Won",
        "KRW": "South Korean Won",
        "KWD": "Kuwaiti Dinar",
        "KYD": "Cayman Islands Dollar",
        "KZT": "Kazakhstani Tenge",
        "LAK": "Laotian Kip",
        "LBP": "Lebanese Pound",
        "LKR": "Sri Lankan Rupee",
        "LRD": "Liberian Dollar",
        "LSL": "Lesotho Loti",
        "LTL": "Lithuanian Litas",
        "LVL": "Latvian Lats",
        "LYD": "Libyan Dinar",
        "MAD": "Moroccan Dirham",
        "MDL": "Moldovan Leu",
        "MGA": "Malagasy Ariary",
        "MKD": "Macedonian Denar",
        "MMK": "Myanma Kyat",
        "MNT": "Mongolian Tugrik",
        "MOP": "Macanese Pataca",
        "MRO": "Mauritanian Ouguiya",
        "MTL": "Maltese Lira",
        "MUR": "Mauritian Rupee",
        "MVR": "Maldivian Rufiyaa",
        "MWK": "Malawian Kwacha",
        "MXN": "Mexican Peso",
        "MYR": "Malaysian Ringgit",
        "MZN": "Mozambican Metical",
        "NAD": "Namibian Dollar",
        "NGN": "Nigerian Naira",
        "NIO": "Nicaraguan Córdoba",
        "NOK": "Norwegian Krone",
        "NPR": "Nepalese Rupee",
        "NZD": "New Zealand Dollar",
        "OMR": "Omani Rial",
        "PAB": "Panamanian Balboa",
        "PEN": "Peruvian Nuevo Sol",
        "PGK": "Papua New Guinean Kina",
        "PHP": "Philippine Peso",
        "PKR": "Pakistani Rupee",
        "PLN": "Polish Zloty",
        "PYG": "Paraguayan Guarani",
        "QAR": "Qatari Rial",
        "RON": "Romanian Leu",
        "RSD": "Serbian Dinar",
        "RUB": "Russian Ruble",
        "RWF": "Rwandan Franc",
        "SAR": "Saudi Riyal",
        "SBD": "Solomon Islands Dollar",
        "SCR": "Seychellois Rupee",
        "SDG": "Sudanese Pound",
        "SEK": "Swedish Krona",
        "SGD": "Singapore Dollar",
        "SHP": "Saint Helena Pound",
        "SLL": "Sierra Leonean Leone",
        "SOS": "Somali Shilling",
        "SRD": "Surinamese Dollar",
        "STD": "S?o Tomé and Príncipe Dobra",
        "SVC": "Salvadoran Colón",
        "SYP": "Syrian Pound",
        "SZL": "Swazi Lilangeni",
        "THB": "Thai Baht",
        "TJS": "Tajikistani Somoni",
        "TMT": "Turkmenistani Manat",
        "TND": "Tunisian Dinar",
        "TOP": "Tongan Pa?anga",
        "TRY": "Turkish Lira",
        "TTD": "Trinidad and Tobago Dollar",
        "TWD": "New Taiwan Dollar",
        "TZS": "Tanzanian Shilling",
        "UAH": "Ukrainian Hryvnia",
        "UGX": "Ugandan Shilling",
        "USD": "United States Dollar",
        "UYU": "Uruguayan Peso",
        "UZS": "Uzbekistan Som",
        "VEF": "Venezuelan Bolívar Fuerte",
        "VND": "Vietnamese Dong",
        "VUV": "Vanuatu Vatu",
        "WST": "Samoan Tala",
        "XAF": "CFA Franc BEAC",
        "XAG": "Silver (troy ounce)",
        "XAU": "Gold (troy ounce)",
        "XCD": "East Caribbean Dollar",
        "XDR": "Special Drawing Rights",
        "XOF": "CFA Franc BCEAO",
        "XPF": "CFP Franc",
        "YER": "Yemeni Rial",
        "ZAR": "South African Rand",
        "ZMK": "Zambian Kwacha (pre-2013)",
        "ZMW": "Zambian Kwacha",
        "ZWL": "Zimbabwean Dollar"
    };

    // $.getJSON('https://openexchangerates.org/api/currencies.json?app_id=' + apiKey, function (currencies) {
        // cache the select el
        var targetSelect = $('select[name=targetUnit]'),
            options = [];

        // create options
        $.each(currencies, function (index, value) {
            if (index === 'USD') { return; }

            options.push('<option value="' + index + '">' + value + '</option>');
        });

        // append all currencies
        $.each(options, function (index, option) {
            targetSelect.append(option);
        });
    // });
};

var getExchangeRates = function() {
    var iExchangeRates = {
        "disclaimer": "Exchange rates are provided for informational purposes only, and do not constitute financial advice of any kind. Although every attempt is made to ensure quality, NO guarantees are given whatsoever of accuracy, validity, availability, or fitness for any purpose - please use at your own risk. All usage is subject to your acceptance of the Terms and Conditions of Service, available at: https://openexchangerates.org/terms/",
        "license": "Data sourced from various providers with public-facing APIs; copyright may apply; resale is prohibited; no warranties given of any kind. Bitcoin data provided by http://coindesk.com. All usage is subject to your acceptance of the License Agreement available at: https://openexchangerates.org/license/",
        "timestamp": 1430222462,
        "base": "USD",
        "rates": {
            "AED": 3.673077,
            "AFN": 57.8936,
            "ALL": 128.643199,
            "AMD": 474.071998,
            "ANG": 1.7895,
            "AOA": 109.236875,
            "ARS": 8.903756,
            "AUD": 1.258409,
            "AWG": 1.792375,
            "AZN": 1.051,
            "BAM": 1.79175,
            "BBD": 2,
            "BDT": 77.79008,
            "BGN": 1.789802,
            "BHD": 0.377003,
            "BIF": 1567.1,
            "BMD": 1,
            "BND": 1.325146,
            "BOB": 6.903363,
            "BRL": 2.922365,
            "BSD": 1,
            "BTC": 0.0044594699,
            "BTN": 63.2698,
            "BWP": 9.826518,
            "BYR": 14338.783333,
            "BZD": 1.994152,
            "CAD": 1.207647,
            "CDF": 924.738,
            "CHF": 0.955977,
            "CLF": 0.024598,
            "CLP": 609.107594,
            "CNY": 6.184032,
            "COP": 2422.833333,
            "CRC": 530.564485,
            "CUC": 1,
            "CUP": 1.000013,
            "CVE": 100.968874,
            "CZK": 25.15236,
            "DJF": 177.388401,
            "DKK": 6.827393,
            "DOP": 44.73476,
            "DZD": 97.70528,
            "EEK": 14.350975,
            "EGP": 7.62576,
            "ERN": 15.1151,
            "ETB": 20.49337,
            "EUR": 0.913775,
            "FJD": 2.035857,
            "FKP": 0.653991,
            "GBP": 0.653991,
            "GEL": 2.3062,
            "GGP": 0.653991,
            "GHS": 3.846319,
            "GIP": 0.653991,
            "GMD": 43.10032,
            "GNF": 7206.566589,
            "GTQ": 7.760088,
            "GYD": 206.070627,
            "HKD": 7.75054,
            "HNL": 21.94868,
            "HRK": 6.94506,
            "HTG": 47.35372,
            "HUF": 275.909398,
            "IDR": 12967.433333,
            "ILS": 3.893316,
            "IMP": 0.653991,
            "INR": 63.22275,
            "IQD": 1179.417567,
            "IRR": 28242.333333,
            "ISK": 134.430999,
            "JEP": 0.653991,
            "JMD": 115.053701,
            "JOD": 0.70837,
            "JPY": 118.9253,
            "KES": 94.345319,
            "KGS": 60.911267,
            "KHR": 4019.321601,
            "KMF": 450.419481,
            "KPW": 900.09,
            "KRW": 1070.533324,
            "KWD": 0.301819,
            "KYD": 0.821806,
            "KZT": 185.8141,
            "LAK": 8096.605033,
            "LBP": 1506.835,
            "LKR": 133.057801,
            "LRD": 84.720001,
            "LSL": 11.94333,
            "LTL": 2.9337,
            "LVL": 0.643844,
            "LYD": 1.368121,
            "MAD": 9.862078,
            "MDL": 18.13809,
            "MGA": 3097.02665,
            "MKD": 56.36307,
            "MMK": 1078.16625,
            "MNT": 1959,
            "MOP": 7.971676,
            "MRO": 312.289533,
            "MTL": 0.392388,
            "MUR": 35.69003,
            "MVR": 15.291575,
            "MWK": 440.3966,
            "MXN": 15.33003,
            "MYR": 3.547813,
            "MZN": 35.16,
            "NAD": 11.94333,
            "NGN": 198.8076,
            "NIO": 26.86055,
            "NOK": 7.69085,
            "NPR": 100.94827,
            "NZD": 1.300323,
            "OMR": 0.384975,
            "PAB": 1,
            "PEN": 3.133862,
            "PGK": 2.689105,
            "PHP": 44.24327,
            "PKR": 101.734001,
            "PLN": 3.666562,
            "PYG": 5012.651634,
            "QAR": 3.640521,
            "RON": 4.026788,
            "RSD": 110.1237,
            "RUB": 51.93987,
            "RWF": 690.28424,
            "SAR": 3.749982,
            "SBD": 7.682191,
            "SCR": 13.65169,
            "SDG": 5.952905,
            "SEK": 8.587753,
            "SGD": 1.323432,
            "SHP": 0.653991,
            "SLL": 4355,
            "SOS": 705.511795,
            "SRD": 3.2825,
            "STD": 22450.7,
            "SVC": 8.705745,
            "SYP": 216.67175,
            "SZL": 11.94343,
            "THB": 32.60361,
            "TJS": 6.2207,
            "TMT": 3.499833,
            "TND": 1.940177,
            "TOP": 2.02569,
            "TRY": 2.677608,
            "TTD": 6.329811,
            "TWD": 30.51621,
            "TZS": 1970.796675,
            "UAH": 22.73687,
            "UGX": 2999.176667,
            "USD": 1,
            "UYU": 26.39735,
            "UZS": 2508.48666,
            "VEF": 6.318453,
            "VND": 21596.666667,
            "VUV": 105.765,
            "WST": 2.473369,
            "XAF": 601.369996,
            "XAG": 0.06093956,
            "XAU": 0.00083082,
            "XCD": 2.70102,
            "XDR": 0.71881,
            "XOF": 601.294376,
            "XPF": 109.278749,
            "YER": 214.9428,
            "ZAR": 11.93722,
            "ZMK": 5252.024745,
            "ZMW": 7.443144,
            "ZWL": 322.355006
        }
    }

    // $.getJSON('https://openexchangerates.org/api/latest.json?app_id=' + apiKey, function (iExchangeRates) {
        exchangeRates = iExchangeRates.rates;
    // });
};

var convert = function() {
    var amount = +$('input[name=amount]').val(),
        amountUnit = $('select[name=amountUnit]').val(),
        targetUnit = $('select[name=targetUnit]').val();

    return amount * exchangeRates[targetUnit];
};

var showResult = function() {
    var label = $('#result');

    label.text(convert());
    label.css('visibility', 'visible').hide().fadeIn('slow');
};

var hideResult = function() {
    $('#result').css('visibility', 'hidden');
};

var registerClickEventHandler = function() {
    $('button').click(showResult);
    $('input[name=amount]').change(hideResult);
    $('select[name=amountUnit]').change(hideResult);
    $('select[name=targetUnit]').change(hideResult);
};

$(document).ready(function() {
    // get data
    getCurrencies();
    getExchangeRates();

    // register events handlers
    registerClickEventHandler();
});